version: "3"
services:
  frontend:
    container_name: arcadia
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - /app/node_modules
