// login,logout
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

// check auth
export const REQUEST_CHECK_AUTH = 'REQUEST_CHECK_AUTH';

// register
export const REQUEST_REGISTER = 'REQUEST_REGISTER';
export const REQUEST_REGISTER_SUCCESS = 'REQUEST_REGISTER_SUCCESS';
export const REQUEST_REGISTER_FAILED = 'REQUEST_REGISTER_FAILED';
